missing dependency on pyyaml
UMR-CNRM/bronx pull request #10
Opened 2024-12-13 11:09 UTC by AlexandreMary

2025-01-09 09:34 UTC, tlestang requested changes

2025-01-09 09:34 UTC, tlestang commented on src/bronx/syntax/decorators.py
> +
Ce décorateur est-t-il utilisé pour des méthodes de classes définies dans bronx?

J'ai du mal à comprendre le besoin d'utiliser une autre fonction d'initialisation `_actual_init` plutot que `__init__` -- ça me parait étrange. En tous cas, si ce décorateur reste dans bronx, il faudrait à mon avis que la docstring donne un exemple, ou a minima explique pourquoi il est utile.

2025-01-09 09:34 UTC, tlestang commented on pyproject.toml
> +    "pyyaml",
Du coup `matplotlib` aussi non?

2025-01-15 10:13 UTC, AlexandreMary commented on pyproject.toml
> +    "pyyaml",
De manière optionnelle oui. Mais tout code qui ferait appel à bronx pour ces fonctions matplotlib utiliserait déjà matplotlib, donc c'est moins indispensable.
Pour pyyaml c'est simplement qu'un
`from bronx.datagrip.misc import read_dict_in_CSV`
dans epygram lève une `ModuleNotFoundError: No module named 'yaml'`

2025-01-15 10:20 UTC, AlexandreMary commented on src/bronx/syntax/decorators.py
> +
L'idée c'est de faire une "delayed init", en n'initialisant certaines choses (typiquement, lire un fichier de définitions GRIB) que lorsqu'on en a réellement besoin.
En fait je n'en ai réellement besoin que dans certaines classes d'epygram, donc je peux l'y garder, mais je pensais que ça pouvait être utile par ailleurs (et que la docstring était assez explicite).

2025-03-21 11:06 UTC, AlexandreMary commented
Actually I just realised `numpy` is also missing among dependencies: although I don't know what's done about that in datagrip/namelist.py (it doesn't seem used).
We should resume about tis PR btw, to be discussed.

2025-05-19 10:39 UTC, tlestang commented
Decided that this was good enough and not worth nitpicking too much about!

2025-05-19 10:40 UTC, merged